(self.AMP=self.AMP||[]).push({n:"amp-lightbox",v:"2011252111002",f:(function(AMP,_){
'use strict';var f,aa="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b};function ba(a){for(var b=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global],c=0;c<b.length;++c){var d=b[c];if(d&&d.Math==Math)return}(function(){throw Error("Cannot find global object");})()}ba(this);"function"===typeof Symbol&&Symbol("x");var m;
if("function"==typeof Object.setPrototypeOf)m=Object.setPrototypeOf;else{var n;a:{var ca={a:!0},p={};try{p.__proto__=ca;n=p.a;break a}catch(a){}n=!1}m=n?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var q=m;
function r(a,b){a.prototype=aa(b.prototype);a.prototype.constructor=a;if(q)q(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.Pa=b.prototype}var t;function u(a,b){var c=b=void 0===b?"":b;try{return decodeURIComponent(a)}catch(d){return c}};var da=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;function v(a){var b=Object.create(null);if(!a)return b;for(var c;c=da.exec(a);){var d=u(c[1],c[1]),e=c[2]?u(c[2].replace(/\+/g," "),c[2]):"";b[d]=e}return b};var w="";
function x(a){var b=a||self;if(b.__AMP_MODE)var c=b.__AMP_MODE;else{c=v(b.location.originalHash||b.location.hash);var d=v(b.location.search);w||(w=b.AMP_CONFIG&&b.AMP_CONFIG.v?b.AMP_CONFIG.v:"012011252111002");c={localDev:!1,development:!!(0<=["1","actions","amp","amp4ads","amp4email"].indexOf(c.development)||b.AMP_DEV_MODE),examiner:"2"==c.development,esm:!1,geoOverride:c["amp-geo"],minified:!0,lite:void 0!=d.amp_lite,test:!1,log:c.log,version:"2011252111002",rtvVersion:w};c=b.__AMP_MODE=c}return c}
;function ea(a){return a?Array.prototype.slice.call(a):[]};var y=self.AMP_CONFIG||{},fa=("string"==typeof y.cdnProxyRegex?new RegExp(y.cdnProxyRegex):y.cdnProxyRegex)||/^https:\/\/([a-zA-Z0-9_-]+\.)?cdn\.ampproject\.org$/;function ha(a){if(self.document&&self.document.head&&(!self.location||!fa.test(self.location.origin))){var b=self.document.head.querySelector('meta[name="'+a+'"]');b&&b.getAttribute("content")}}y.cdnUrl||ha("runtime-host");y.geoApiUrl||ha("amp-geo-api");self.__AMP_LOG=self.__AMP_LOG||{user:null,dev:null,userForEmbed:null};var z=self.__AMP_LOG;function ia(){if(!z.user)throw Error("failed to call initLogConstructor");return z.user}function A(){if(z.dev)return z.dev;throw Error("failed to call initLogConstructor");};function ja(){var a,b;this.promise=new Promise(function(c,d){a=c;b=d});this.resolve=a;this.reject=b};function B(){this.o=null}f=B.prototype;f.add=function(a){var b=this;this.o||(this.o=[]);this.o.push(a);return function(){b.remove(a)}};f.remove=function(a){this.o&&(a=this.o.indexOf(a),-1<a&&this.o.splice(a,1))};f.removeAll=function(){this.o&&(this.o.length=0)};f.fire=function(a){if(this.o)for(var b=this.o,c=0;c<b.length;c++)(0,b[c])(a)};f.getHandlerCount=function(){return this.o?this.o.length:0};function C(a,b){a=a.__AMP_TOP||(a.__AMP_TOP=a);return E(a,b)}function F(a,b){var c=G(a);c=ka(c);return E(c,b)}function la(a){a=G(a);a=ka(a);return ma(a,"action")?E(a,"action"):null}function G(a){return a.nodeType?C((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}function ka(a){a=G(a);return a.isSingleDoc()?a.win:a}
function E(a,b){ma(a,b);var c=a.__AMP_SERVICES;c||(c=a.__AMP_SERVICES={});a=c[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj}function ma(a,b){a=a.__AMP_SERVICES&&a.__AMP_SERVICES[b];return!(!a||!a.ctor&&!a.obj)};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
var na=Object.prototype.hasOwnProperty;function H(a){return a||{}};function oa(a,b){for(;a&&void 0!==a;a=a.parentElement)if(b(a))return a;return null}function qa(a){return a.closest?a.closest(".i-amphtml-fie"):oa(a,function(b){var c=b.matches||b.webkitMatchesSelector||b.mozMatchesSelector||b.msMatchesSelector||b.oMatchesSelector;return c?c.call(b,".i-amphtml-fie"):!1})}function I(a){try{a.focus()}catch(b){}};function J(a){return F(a,"owners")};function K(a,b){var c=this;this.ya=C(a,"timer");this.Fa=b;this.Ea=0;this.P=-1;this.da=0;this.ja=!1;this.Aa=function(){c.$()}}K.prototype.isPending=function(){return-1!=this.P};K.prototype.schedule=function(a){var b=a||this.Ea;this.ja&&10>b&&(b=10);var c=Date.now()+b;return!this.isPending()||-10>c-this.da?(this.cancel(),this.da=c,this.P=this.ya.delay(this.Aa,b),!0):!1};K.prototype.$=function(){this.P=-1;this.da=0;this.ja=!0;this.Fa();this.ja=!1};
K.prototype.cancel=function(){this.isPending()&&(this.ya.cancel(this.P),this.P=-1)};function ra(a,b){for(var c=0;c<a.length;c++)if(b(a[c],c,a))return c;return-1};var L;function sa(a){if(void 0!==L)return L;L=!1;try{var b={get passive(){L=!0;return!1}};a.addEventListener("test-options",null,b);a.removeEventListener("test-options",null,b)}catch(c){}return L};function ta(a,b,c,d){this.type=a;this.data=b;this.time=c;this.event=d}
function ua(a,b,c){this.C=a;this.h=[];this.L=[];this.A=[];this.j=[];this.l=null;this.Ma=b;this.Na=c;this.aa=!1;this.$=new K(a.ownerDocument.defaultView,this.ta.bind(this));this.va=new B;this.O=Object.create(null);this.ra=this.La.bind(this);this.pa=this.Ja.bind(this);this.qa=this.Ka.bind(this);this.oa=this.Ia.bind(this);var d=sa(a.ownerDocument.defaultView);this.C.addEventListener("touchstart",this.ra,d?{passive:!0}:!1);this.C.addEventListener("touchend",this.pa);this.C.addEventListener("touchmove",
this.qa,d?{passive:!0}:!1);this.C.addEventListener("touchcancel",this.oa);this.fa=!1}function va(a){var b=void 0===b?!1:b;var c=void 0===c?!1:c;var d=a.__AMP_Gestures;d||(d=new ua(a,b,c),a.__AMP_Gestures=d);return d}f=ua.prototype;f.cleanup=function(){this.C.removeEventListener("touchstart",this.ra);this.C.removeEventListener("touchend",this.pa);this.C.removeEventListener("touchmove",this.qa);this.C.removeEventListener("touchcancel",this.oa);delete this.C.__AMP_Gestures;this.$.cancel()};
f.onGesture=function(a,b){var c=new a(this),d=c.getType(),e=this.O[d];e||(this.h.push(c),e=new B,this.O[d]=e);return e.add(b)};f.removeGesture=function(a){var b=(new a(this)).getType();if(a=this.O[b]){a.removeAll();a=ra(this.h,function(c){return c.getType()==b});if(0>a)return!1;this.h.splice(a,1);this.A.splice(a,1);this.j.splice(a,1);this.L.splice(a,1);delete this.O[b];return!0}return!1};f.onPointerDown=function(a){return this.va.add(a)};
f.La=function(a){var b=Date.now();this.aa=!1;this.va.fire(a);for(var c=0;c<this.h.length;c++)if(!this.A[c]&&(this.j[c]&&this.j[c]<b&&M(this,c),this.h[c].onTouchStart(a))){var d=c;this.L[d]=!0;this.j[d]=0}N(this,a)};f.Ka=function(a){for(var b=Date.now(),c=0;c<this.h.length;c++)this.L[c]&&(this.j[c]&&this.j[c]<b?M(this,c):this.h[c].onTouchMove(a)||M(this,c));N(this,a)};
f.Ja=function(a){for(var b=Date.now(),c=0;c<this.h.length;c++)if(this.L[c])if(this.j[c]&&this.j[c]<b)M(this,c);else{this.h[c].onTouchEnd(a);var d=!this.j[c],e=this.j[c]<b;this.l!=this.h[c]&&(d||e)&&M(this,c)}N(this,a)};f.Ia=function(a){for(var b=0;b<this.h.length;b++){var c=b;this.A[c]=0;M(this,c)}N(this,a)};
function N(a,b){var c=!!a.l||a.aa;a.aa=!1;if(!c)for(var d=Date.now(),e=0;e<a.h.length;e++)if(a.A[e]||a.j[e]&&a.j[e]>=d){c=!0;break}c?(b.stopPropagation(),a.Ma||b.preventDefault()):a.Na&&b.stopPropagation();a.fa&&(a.fa=!1,a.ta())}
f.ta=function(){for(var a=Date.now(),b=-1,c=0;c<this.h.length;c++)if(!this.A[c])this.j[c]&&this.j[c]<a&&M(this,c);else if(-1==b||this.A[c]>this.A[b])b=c;if(-1!=b){var d=0;for(c=0;c<this.h.length;c++)!this.A[c]&&this.L[c]&&(d=Math.max(d,this.j[c]-a));if(2>d){a=b;c=this.h[a];for(var e=0;e<this.h.length;e++)if(e!=a){var g=e;this.A[g]=0;M(this,g)}this.A[a]=0;this.j[a]=0;this.l=c;c.acceptStart()}else this.$.schedule(d)}};function M(a,b){a.L[b]=!1;a.j[b]=0;a.A[b]||a.h[b].acceptCancel()}
function O(a,b){this.Oa=a;this.Z=b}f=O.prototype;f.getType=function(){return this.Oa};f.signalReady=function(a){var b=this.Z;if(b.l)this.acceptCancel();else{for(var c=Date.now(),d=0;d<b.h.length;d++)b.h[d]==this&&(b.A[d]=c+a,b.j[d]=0);b.fa=!0}};f.signalPending=function(a){var b=this.Z;if(b.l)this.acceptCancel();else for(var c=Date.now(),d=0;d<b.h.length;d++)b.h[d]==this&&(b.j[d]=c+a)};f.signalEnd=function(){var a=this.Z;a.l==this&&(a.l=null,a.aa=!0)};
f.signalEmit=function(a,b){var c=this.Z.O[this.getType()];c&&c.fire(new ta(this.getType(),a,Date.now(),b))};f.acceptStart=function(){};f.acceptCancel=function(){};f.onTouchStart=function(){return!1};f.onTouchMove=function(){return!1};f.onTouchEnd=function(){};function wa(a,b,c){1>b&&(b=1);var d=.5+Math.min(b/33.34,.5);return a/b*d+c*(1-d)};function P(a,b,c,d){O.call(this,a,b);this.ua=c;this.za=d;this.l=!1;this.na=this.ma=this.ga=this.Y=this.xa=this.ia=this.ha=this.I=this.H=this.K=this.J=0}r(P,O);f=P.prototype;f.onTouchStart=function(a){a=a.touches;return this.l&&a&&1<a.length?!0:a&&1==a.length?(this.xa=Date.now(),this.J=a[0].clientX,this.K=a[0].clientY,!0):!1};
f.onTouchMove=function(a){var b=a.touches;if(b&&1<=b.length){var c=b[0];b=c.clientX;c=c.clientY;this.H=b;this.I=c;if(this.l)Q(this,!1,!1,a);else if(a=Math.abs(b-this.J),b=Math.abs(c-this.K),this.ua&&this.za)(8<=a||8<=b)&&this.signalReady(-10);else if(this.ua)if(8<=a&&a>b)this.signalReady(-10);else{if(8<=b)return!1}else if(this.za)if(8<=b&&b>a)this.signalReady(-10);else{if(8<=a)return!1}else return!1;return!0}return!1};
f.onTouchEnd=function(a){var b=a.touches;b&&0==b.length&&this.l&&(this.l=!1,Q(this,!1,!0,a),this.signalEnd())};f.acceptStart=function(){this.l=!0;this.ha=this.J;this.ia=this.K;this.ga=this.xa;this.J=this.H;this.K=this.I;Q(this,!0,!1,null)};f.acceptCancel=function(){this.l=!1};
function Q(a,b,c,d){a.Y=Date.now();var e=a.Y-a.ga;if(!c&&4<e||c&&16<e){var g=wa(a.H-a.ha,e,a.ma),h=wa(a.I-a.ia,e,a.na);if(!c||32<e||0!=g||0!=h)a.ma=1E-4<Math.abs(g)?g:0,a.na=1E-4<Math.abs(h)?h:0;a.ha=a.H;a.ia=a.I;a.ga=a.Y}a.signalEmit({first:b,last:c,time:a.Y,deltaX:a.H-a.J,deltaY:a.I-a.K,startX:a.J,startY:a.K,lastX:a.H,lastY:a.I,velocityX:a.ma,velocityY:a.na},d)}function xa(a){P.call(this,"swipe-xy",a,!0,!0)}r(xa,P);var R,ya="Webkit webkit Moz moz ms O o".split(" ");function za(a,b,c){if(b.startsWith("--"))return b;R||(R=Object.create(null));var d=R[b];if(!d||c){d=b;if(void 0===a[b]){var e=b.charAt(0).toUpperCase()+b.slice(1);a:{for(var g=0;g<ya.length;g++){var h=ya[g]+e;if(void 0!==a[h]){e=h;break a}}e=""}var k=e;void 0!==a[k]&&(d=k)}c||(R[b]=d)}return d}function Aa(a,b){a=a.style;for(var c in b)a.setProperty(za(a,c),b[c].toString(),"important")}
function S(a,b,c){(b=za(a.style,b,void 0))&&(b.startsWith("--")?a.style.setProperty(b,c):a.style[b]=c)}function T(a,b){for(var c in b)S(a,c,b[c])}function V(a){"display"in a&&A().error("STYLE","`display` style detected in styles. You must use toggle instead.");return a}function Ba(a){var b=!0;void 0===b&&(b=a.hasAttribute("hidden"));b?a.removeAttribute("hidden"):a.setAttribute("hidden","")}function Ca(a){for(var b=["transition"],c=0;c<b.length;c++)S(a,b[c],null)};function Da(a,b){function c(){d=0;var h=500-(a.Date.now()-e);if(0<h)d=a.setTimeout(c,h);else{var k=g;g=null;b.apply(null,k)}}var d=0,e=0,g=null;return function(h){for(var k=[],l=0;l<arguments.length;++l)k[l-0]=arguments[l];e=a.Date.now();g=k;d||(d=a.setTimeout(c,500))}};var W;H({c:!0,v:!0,a:!0,ad:!0});function Ea(a){return a.classList.contains("i-amphtml-fie")||!!qa(a)};var Fa=['<i-amphtml-ad-close-header role=button tabindex=0 aria-label="Close Ad"><div>Ad</div><i-amphtml-ad-close-button class=amp-ad-close-button></i-amphtml-ad-close-button></i-amphtml-ad-close-header>'],X={"fade-in":{openStyle:H({opacity:1}),closedStyle:H({opacity:0}),durationSeconds:.1},"fly-in-bottom":{openStyle:H({transform:"translate(0, 0)"}),closedStyle:H({transform:"translate(0, 100%)"}),durationSeconds:.2},"fly-in-top":{openStyle:H({transform:"translate(0, 0)"}),closedStyle:H({transform:"translate(0, -100%)"}),
durationSeconds:.2}};
function Y(a){var b=AMP.BaseElement.call(this,a)||this;b.la=null;b.B=null;b.N=b.win.document;b.R=null;b.ca=-1;b.S=!1;b.V=null;b.U=null;b.X=null;b.W=null;b.ea=null;b.G=!1;b.D=0;b.ba=0;b.ka=null;b.T=(a.getAttribute("animate-in")||"fade-in").toLowerCase();b.m=null;b.F=null;b.M=null;var c=C(b.win,"platform");b.Ga=c.isIos();b.sa=Da(b.win,function(){var d=ia().assertElement(b.B,"E#19457 this.container_"),e=J(b.element);e.scheduleLayout(b.element,d);e.scheduleResume(b.element,d)});return b}r(Y,AMP.BaseElement);
f=Y.prototype;f.buildCallback=function(){var a=this;this.user().assert(na.call(X,this.T),"Invalid `animate-in` value %s",this.T);this.element.classList.add("i-amphtml-overlay");this.R=la(this.element);Ga(this);this.registerDefaultAction(function(b){return Ha(a,b.trust,b.caller)},"open");this.registerAction("close",function(b){return a.close(b.trust)});this.R.addToAllowlist("AMP-LIGHTBOX",["open","close"],["email"])};
function Ia(a){ea(a.element.getElementsByClassName("i-amphtml-element")).forEach(function(b){J(a.element).setOwner(b,a.element)})}
function Ja(a){if(!a.B){var b=a.element;a.G=b.hasAttribute("scrollable");var c=a.getRealChildren();a.B=b.ownerDocument.createElement("div");a.G||a.applyFillContent(a.B);b.appendChild(a.B);c.forEach(function(d){a.B.appendChild(d)});a.G&&(Ia(a),b.classList.add("i-amphtml-scrollable"),b.addEventListener("amp:dom-update",function(){Ia(a);Z(a,a.D)}),b.addEventListener("scroll",a.wa.bind(a)));if(!a.G)va(b).onGesture(xa,function(){});Ka(a)}}
f.layoutCallback=function(){t||(t=Promise.resolve(void 0));var a=t;return a};function Ha(a,b,c){if(!a.S){Ja(a);a.V=a.Da.bind(a);a.N.documentElement.addEventListener("keydown",a.V);a.X=a.Ha.bind(a);a.N.documentElement.addEventListener("focusin",a.X);c&&(a.ea=c);var d=new ja,e=d.promise,g=d.resolve;a.getViewport().enterLightboxMode(a.element,e).then(function(){return La(a,g,b)})}}f.mutatedAttributesCallback=function(a){var b=a.open;void 0!==b&&(b?Ha(this,2,document.activeElement):this.close(2))};
function Ma(a){var b=a.B.querySelector("[autofocus]");b&&I(b)}
function La(a,b,c){function d(){a.sa();b()}var e=a.element,g=X[a.T],h=g.durationSeconds,k=g.openStyle,l=g.closedStyle,D=Object.keys(k).map(function(U){return U+" "+h+"s ease-in"}).join(",");a.ba++;a.G&&S(e,"webkitOverflowScrolling","touch");S(e,"transition",D);T(e,V(l));Ba(e);a.mutateElement(function(){e.scrollTop=0});Ma(a);a.mutateElement(function(){T(e,V(k))});g=a.B;a.G&&(a.wa(),Z(a,a.D));e.addEventListener("transitionend",d);e.addEventListener("animationend",d);var pa=J(a.element);pa.scheduleLayout(a.element,
g);pa.scheduleResume(a.element,g);Na(a,"lightboxOpen",c);F(a.getAmpDoc(),"history").push(function(){return a.close(c)}).then(function(U){a.ca=U});Oa(a);Pa(a);Qa(a);a.S=!0}function Ka(a){var b=a.element;if(null!=b.getAttribute("close-button")){var c=b.ownerDocument||b;W&&W.ownerDocument===c||(W=c.createElement("div"));c=W;c.innerHTML=Fa[0];var d=c.firstElementChild;c.removeChild(d);a.m=d;b.insertBefore(a.m,a.B)}}
function Oa(a){if(a.m){a.U=a.Ca.bind(a);a.m.addEventListener("keydown",a.U);var b;a.measureMutateElement(function(){b=a.m.getBoundingClientRect().height},function(){a.m.classList.add("amp-ad-close-header");Aa(a.B,{"margin-top":b+"px","min-height":"calc(100vh - "+(b+"px)")})})}}function Qa(a){if(a.M||a.m)a.W=a.Ba.bind(a),a.F.addEventListener("click",a.W)}function Ra(a){if(a.M||a.m)a.F.removeEventListener("click",a.W),a.W=null,a.m&&(a.m.removeEventListener("keydown",a.U),a.U=null)}f.Ba=function(){this.close(3)};
f.Da=function(a){"Escape"==a.key&&(a.preventDefault(),this.close(3))};f.Ca=function(a){"Enter"==a.key&&(a.preventDefault(),this.close(3))};f.close=function(a){var b=this;this.S&&(this.G&&S(this.element,"webkitOverflowScrolling",""),this.getViewport().leaveLightboxMode(this.element).then(function(){return Sa(b,a)}))};
function Sa(a,b){function c(){e==a.ba&&(a.collapse(),a.sa())}var d=a.element,e=++a.ba;Ta(a)?(Ca(d),c()):(d.addEventListener("transitionend",c),d.addEventListener("animationend",c));T(d,V(X[a.T].closedStyle));-1!=a.ca&&F(a.getAmpDoc(),"history").pop(a.ca);a.N.documentElement.removeEventListener("keydown",a.V);a.V=null;a.N.documentElement.removeEventListener("focusin",a.X);a.X=null;Ra(a);J(a.element).schedulePause(a.element,a.B);a.S=!1;Na(a,"lightboxClose",b);a.ea&&I(a.ea)}
function Ta(a){return"inabox"==x(a.win).runtime||Ea(a.element)}f.Ha=function(){this.element.contains(document.activeElement)||this.close(3)};
function Pa(a){if(!a.element.contains(document.activeElement)){a:if(a.F)var b=a.F;else if(a.m)b=a.m;else{b=a.element;for(var c=b.querySelectorAll("[on]"),d=0;d<c.length;d++){var e=c[d];if(a.R.hasResolvableActionForTarget(e,"tap",b,e.parentElement)){b=e;break a}}b=void 0}a.F=b;a.F||(b=a.element.getAttribute("data-close-button-aria-label")||"Close the modal",c=a.N.createElement("button"),c.textContent=b,c.classList.add("i-amphtml-screen-reader"),c.tabIndex=-1,a.M=c,a.element.insertBefore(a.M,a.element.firstChild),
a.F=a.M);I(a.F)}}f.wa=function(){var a=this.element.scrollTop;this.Ga&&(0==a?this.element.scrollTop=1:this.element.scrollHeight==a+this.element.offsetHeight&&(this.element.scrollTop=a-1));this.D=a;null===this.ka&&Ua(this,a)};
function Ua(a,b){a.ka=C(a.win,"timer").delay(function(){if(30>Math.abs(b-a.D)){A().fine("amp-lightbox","slow scrolling: %s - %s",b,a.D);a.ka=null;var c=a.D;A().fine("amp-lightbox","update_");Z(a,c);a.D=c}else A().fine("amp-lightbox","fast scrolling: %s - %s",b,a.D),Ua(a,a.D)},100)}function Z(a,b){var c=[];Va(a,b,function(d){c.push(d);J(a.element).scheduleLayout(a.element,d)})}
function Va(a,b,c){a.la||(a.la={width:a.element.clientWidth,height:a.element.clientHeight});for(var d=a.la.height,e=ea(a.element.getElementsByClassName("i-amphtml-element")),g=0;g<e.length;g++){for(var h=e[g],k=0,l=h;l&&a.element.contains(l);l=l.offsetParent)k+=l.offsetTop;var D=2*d;k+h.offsetHeight>=b-D&&k<=b+D&&c(h)}}function Ga(a){var b=a.win;Ea(a.element)&&Wa(b,b.document.body)}
function Na(a,b,c){var d=a.win;var e="amp-lightbox."+b;var g=H({}),h={detail:g};Object.assign(h,void 0);"function"==typeof d.CustomEvent?e=new d.CustomEvent(e,h):(d=d.document.createEvent("CustomEvent"),d.initCustomEvent(e,!!h.bubbles,!!h.cancelable,g),e=d);a.R.trigger(a.element,b,e,c)}
function Wa(a,b){var c={},d=C(a,"ampdoc").getAmpDoc(b);F(d,"mutator").measureMutateElement(b,function(){c.alreadyTransparent="rgba(0, 0, 0, 0)"==(a.getComputedStyle(b)||Object.create(null))["background-color"]},function(){c.alreadyTransparent||ia().warn("amp-lightbox","The background of the <body> element has been forced to transparent. If you need to set background, use an intermediate container.");Aa(b,{background:"transparent"})})}
(function(a){"inabox"==x().runtime&&Wa(window,document.body);a.registerElement("amp-lightbox",Y,"amp-lightbox{display:none;position:fixed!important;z-index:1000;top:0!important;left:0!important;bottom:0!important;right:0!important}amp-lightbox[scrollable]{overflow-y:auto!important;overflow-x:hidden!important}i-amphtml-ad-close-header{height:60px!important;display:block!important;visibility:visible!important;opacity:0;position:fixed!important;top:0!important;left:0!important;right:0!important;z-index:1000!important;display:-ms-flexbox!important;display:flex!important;-ms-flex-align:center!important;align-items:center!important;-ms-flex-pack:right!important;justify-content:right!important;transition:opacity 0.1s ease-in}[animate-in=fly-in-bottom]>i-amphtml-ad-close-header,[animate-in=fly-in-top]>i-amphtml-ad-close-header{transition-delay:0.2s}.amp-ad-close-header{opacity:1!important;box-sizing:border-box;padding:5px;line-height:40px;background-color:#000;color:#fff;font-family:Helvetica,sans-serif;font-size:12px;cursor:pointer}.amp-ad-close-header>:first-child{margin-left:auto!important;pointer-events:none!important}.amp-ad-close-button{display:block!important;background:url(\"data:image/svg+xml;charset=utf-8,%3Csvg xmlns='http://www.w3.org/2000/svg' width='24' height='24' fill='%23fff'%3E%3Cpath d='M19 6.41L17.59 5 12 10.59 6.41 5 5 6.41 10.59 12 5 17.59 6.41 19 12 13.41 17.59 19 19 17.59 13.41 12z'/%3E%3Cpath d='M0 0h24v24H0z' fill='none'/%3E%3C/svg%3E\") no-repeat;background-position:50%;width:40px;height:40px;pointer-events:none!important;border-radius:40px;margin-left:5px}.amp-ad-close-header:active>.amp-ad-close-button{background-color:hsla(0,0%,100%,0.3)}\n/*# sourceURL=/extensions/amp-lightbox/0.1/amp-lightbox.css*/")})(self.AMP);
})});

//# sourceMappingURL=amp-lightbox-0.1.js.map
